FROM node:22-alpine

WORKDIR /app

# Install dependencies dulu
COPY package*.json ./
RUN npm install

# Copy semua source code
COPY . .

# Expose port Vite
EXPOSE 5173

# Jalankan dev server
CMD ["npm", "run", "dev", "--", "--host"]
